name: equalone
description: "Deep equality, value comparison, and hashCode for any Dart object, collection, List, Map, Set, or data class."
version: 1.2.1
homepage: https://github.com/dartius-dev/equalone
repository: https://github.com/dartius-dev/equalone
issue_tracker: https://github.com/dartius-dev/equalone/issues

topics:
  - equality
  - equals
  - compare
  - deep-equality
  - collection

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ^1.5.0
  collection: ^1.19.1

dev_dependencies:
  test: ^1.25.2


